-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2022-11-18 05:55:13.631

-- tables
-- Table: CLIENTE
CREATE TABLE CLIENTE (
    CODCLI char(4) NOT NULL,
    NOMCLI varchar(50) NOT NULL,
    APECLI varchar(50) NOT NULL,
    DNICLI char(8) NOT NULL,
    EMAILCLI varchar(70) NOT NULL,
    CELCLI char(9) NOT NULL,
    TALCALCLI int NOT NULL,
    ESTCLI char(1) NOT NULL,
    SEXCLI char(1) NOT NULL,
    CONSTRAINT CLIENTE_pk PRIMARY KEY (CODCLI)
) COMMENT 'CONTIENE INFORMACIÓN DEL CLIENTE';

-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    CODPRO char(4) NOT NULL,
    MARPRO varchar(50) NOT NULL,
    PREPRO decimal(8,2) NOT NULL,
    TALPRO int NOT NULL,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY (CODPRO)
) COMMENT 'CONTIENE INFORMACIÓN DEL STOCK O PRODUCTO';

-- Table: VENTA
CREATE TABLE VENTA (
    CODVEN char(4) NOT NULL,
    CODCLI char(4) NOT NULL,
    CODPRO char(4) NOT NULL,
    FECVEN date NOT NULL,
    HORVEN time NOT NULL,
    CLIENTE_CODCLI char(4) NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (CODVEN)
) COMMENT 'CONTIENE INFORMACIÓN DE LA VENTA';

-- foreign keys
-- Reference: VENTA_CLIENTE (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE FOREIGN KEY VENTA_CLIENTE (CLIENTE_CODCLI)
    REFERENCES CLIENTE (CODCLI);

-- Reference: VENTA_PRODUCTO (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_PRODUCTO FOREIGN KEY VENTA_PRODUCTO ()
    REFERENCES PRODUCTO ();

-- End of file.

